spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
##    url: jdbc:mysql://localhost:3306/study_mysql?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
#    url: jdbc:mysql://localhost:13306/codeify?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
#    username: root
#    password: root
# 引入达梦数据源
  datasource:
    url: jdbc:dm://localhost:30236/CODEIFY?useSSL=false&useInformationSchema=true&schema=CODEIFY
    username: SYSDBA
    password: SYSDBA001
    driver-class-name: dm.jdbc.driver.DmDriver
    type: com.zaxxer.hikari.HikariDataSource
#    type: com.alibaba.druid.pool.DruidDataSource

#  data:
##    mongodb:
##      uri: mongodb://localhost:37017/codeify
server:
  port: 8081
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑删除值
      logic-not-delete-value: 0 # 逻辑未删除值
#      schema: CODEIFY
#      table-prefix: CODEIFY.
