INSERT INTO CODEIFY.DEPARTMENT (DEPARTMENT_ID,DEPARTMENT_NAME) VALUES
	 (666,'数据库管理'),
	 (111,'数据库管理111');


insert into CODEIFY.DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME)
values  (666, '数据库管理'),
        (111, '数据库管理111');

